version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    resource_class: 2xlarge+
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update
            apt-get install -y python3 python3-venv git cmake ninja-build g++ python3-dev llvm
            python3 -m venv env
      - run:
          name: Checkout PyTorch
          command: |
            cd ..
            git clone https://github.com/pytorch/pytorch.git --recursive
      - run:
          name: Build PyTorch 
          command: |
            source env/bin/activate
            cd ../pytorch
            pip install -r requirements.txt
            python setup.py install
      - run:
          name: Build and test pytorch/tvm
          command: |
            source env/bin/activate

            git fetch origin master:upstream
            git rebase upstream
            git submodule sync --recursive
            git submodule update --init --recursive

            python setup.py install --cmake
            mkdir -p tvm/build/

            OMP_NUM_THREADS=1 python setup.py test 



